reload_data:
  description: 刷新数据和UI
  fields:
    entity_id:
      description: Name of the weather entity.
      example: 'weather.home'
    api_type:
      description: '请求接口类型：111111 6位数字，每一位只有0或1，1代表需要请求，从左到右依次是：和风实时｜和风空气质量｜和风小时｜和风天级｜和风舒适及穿衣指数|彩云，例如如果不请求和风实时那么为：011111'
      example: '111111'